# cargo deny configuration file to audit dependencies for licensing
[graph]

targets = [
]

#exclude = []
all-features = false
no-default-features = false
#features = []

# The output table provides options for how/if diagnostics are outputted
[output]
feature-depth = 1

[advisories]

ignore = [
]

# This section is considered when running `cargo deny check licenses`
# More documentation for the licenses section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
# List of explicitly allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
# [possible values: any SPDX 3.11 short identifier (+ optional exception)].
allow = [
    # defaults
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",

    # OSI Approved other licenses that have come up
    "BSL-1.0", # Boost Software License 1.0
    "MPL-2.0", # Mozilla Public License 2.0
    "BSD-2-Clause", # BSD 2-Clause "Simplified" License
    "BSD-3-Clause", # BSD 3-Clause "New" or "Revised" License
    "ISC", # ISC License
    "Unicode-DFS-2016", # Unicode-DFS-2016
    "Zlib", # zlib License
    "Unicode-3.0", # Unicode-3.0

    # CC0 is a public domain dedication, so it's allowed everywhere
    "CC0-1.0", # Creative Commons Zero v1.0 Universal


    # OpenSSL is FSF approved, but not OSI approved
    "OpenSSL", # OpenSSL License

]

confidence-threshold = 0.8

exceptions = [
]

# Some crates don't have (easily) machine readable licensing information,
# adding a clarification entry for it allows you to manually specify the
# licensing information
[[licenses.clarify]]
# The package spec the clarification applies to
crate = "ring"

# The SPDX expression for the license requirements of the crate
expression = "MIT AND ISC AND OpenSSL"

# One or more files in the crate's source used as the "source of truth" for
# the license expression. If the contents match, the clarification will be used
# when running the license check, otherwise the clarification will be ignored
# and the crate will be checked normally, which may produce warnings or errors
# depending on the rest of your configuration
license-files = [
# Each entry is a crate relative path, and the (opaque) hash of its contents
{ path = "LICENSE", hash = 0xbd0eed23 }
]

[licenses.private]
# If true, ignores workspace crates that aren't published, or are only
# published to private registries.
# To see how to mark a crate as unpublished (to the official registry),
# visit https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field.
ignore = false
# One or more private registries that you might publish crates to, if a crate
# is only published to private registries, and ignore is true, the crate will
# not have its license(s) checked
registries = [
    #"https://sekretz.com/registry
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = [
]
# List of crates to deny
deny = [
]


skip = [
]


skip-tree = [
]


[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []